spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/order-java-springboot
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true // 운영환경에서는 로거를 통해 로그를 찍어야 함
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug